### ISSUE TITLE
add ability to select the TYP of boundary

### ISSUE THREAD

**Issue by andysouth** [dickoa/rgeoboundaries#1]
Ability to select the type of boundary as specified in the API would be useful.

https://www.geoboundaries.org/api.html

TYP - Optional; defaults to HPSCU. One of HPSCU, HPSCGS, SSCGS, or SSCU. Determines the type of boundary link you receive.
HPSCU - High Precision Single Country Unstadardized. The premier geoBoundaries release, representing the highest precision files available for every country in the world. No standardization is performed on these files, so (for example) two countries may overlap in the case of contested boundaries.
HPSCGS - High Precision Single Country Globally Standardized. A version of geoBoundaries high percision data that has been clipped to the U.S. Department of State boundary file, ensuring no contested boundaries or overlap in the dataset. This globally standardized product may have gaps between countries. If you need a product with no gaps, we recommend our simplified global product.
SSCU - Simplified Single Country Unstandardized. A simplified version of every file available for every country in the world. No standardization is performed on these files, so (for example) two countries may overlap in the case of contested boundaries.
SSCGS - Simplified Single Country Globally Standardized. A version of geoBoundaries simplified data that has been clipped to the U.S. Department of State boundary file, ensuring no contested boundaries or overlap in the dataset. This globally standardized product may have gaps between countries.

**Comment by dickoa** [comment]
Hi Andy,

Thanks a lot for the suggestion, I will update it now.
I also wanted to know if you have some ideas on how to make it easier to use in terms of have pre-downloaded data ? using cache ? etc. I really like what you did with rnaturalearth and I'm not exactly sure I can reproduce something like this for this package.
Please let me know if there's a doc/process I can follow for that.
Thanks again for the suggestion
Ahmadou

**Comment by andysouth** [comment]
Thanks Ahmadou,
We can definitely look into caching later.
I'm currently getting an error that I was going to submit as a separate issue but just trying to make sure it's not a glitch on my side first. 
I'm getting this with the example from the readme :
> sf1 <- rgeoboundaries::geoboundaries(c("mali", "senegal"), adm_lvl = "adm0")
Error in basename(link) : a character vector argument expected 

Andy

**Comment by dickoa** [comment]
I can't reproduce it but I will have a look ASAP. Is it the same type of error when you use
`gb_adm0(c("mali", "senegal"))` ?

**Comment by andysouth** [comment]
Yes. Let me have a look here first. Seems to be just because it's not passing a string to basename. e.g. I get the same if I do `basename(1)`. Maybe it's failing to reach the server from my end.

**Comment by andysouth** [comment]
Ah, so the issue with me (still on R v3.6.3) is that the download links come out as a factor which then causes the error. The added line in between fixes it. Maybe this a result of the recent change to stringsAsFactors. Want me to submit this as a separate issue ?

  links <- get_download_link(country, adm_lvl)
  links <- as.character(links)
  shps <- get_shp_from_link(links)

**Comment by dickoa** [comment]
Not it's fine and thanks a lot for the fix. I just pushed the change and I will add a `type` argument too. Let me know if it works now.
Thanks a lot

**Comment by andysouth** [comment]
Cool yes, the error fixed now :-)

**Comment by andysouth** [comment]
Hi Ahmadou, do you know when you may get to the type argument ? I offered to send someone some data based on it, be good to give them a time estimate. Thanks.

**Comment by dickoa** [comment]
Hi Andy,
 
I already have it locally and doing some tests. I will push it today and work on caching later on.
Thanks

**Comment by andysouth** [comment]
Great, that's perfect, thanks for the update.

**Comment by dickoa** [comment]
I just pushed the code with initial support for types, let me know if it works well and I also added a way to cache download using the `hoardr` package. Let me know if something is not working as expected.
Thanks again

**Comment by dickoa** [comment]
Hi @andysouth,

Did you have the chance to try the new version ? 
Thanks

**Comment by andysouth** [comment]
Thanks and apologies for delay. 
Yes, I tried this out for type = "SSCGS" and type = "SSCU" and it seems to be working :-)
