### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Chilesummits** [dickoa/rgeoboundaries#10]
Calling rgeoboundaries::geoboundaries("Chile") returns:
Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  SSL certificate problem: certificate has expired

**Comment by DanRunfola** [comment]
This was corrected with a SSL fix a while back, closing out fo rnow.  If anyone still sees an SSL issue please let me know!
