### ISSUE TITLE
On CRAN?

### ISSUE THREAD

**Issue by Nowosad** [dickoa/rgeoboundaries#11]
Hi @dickoa -- do you have any plans to release **rgeoboundaries** on CRAN? I am thinking about adding info about this great package to the second edition of the Geocomputation with R book, but I only want to include there packages that are on CRAN. 

If you do not plan to put it to CRAN -- just close this issue;)

**Comment by dickoa** [comment]
Hi @Nowosad 
I plan to submit but it'll be up by January. Happy to notify you when it'll be the case. 
I was waiting for the new geoBoundaries API to be out, I'm refactoring a little bit the package to avoid breaking changes while adding new features from the new v4 API. I will keep you posted, and I'm really excited about the second edition of this masterpiece.
Thanks

**Comment by z3tt** [comment]
Hi @dickoa, that would be great! Especially as NaturalEarth still insists to define the Crimea as Russian, it would be nice to have a simple installation for workshop participants.

**Comment by DanRunfola** [comment]
@z3tt I'm not sure how active dickoa is able to be on this right now, but we're just about to push an update to rgeoboundaries bringing it on to the modern (v5) API.  It's been frozen to geoBoundaries 3.0 for a while, so it's a pretty big upgrade.

Once we get that in the wild, assuming it all doesn't fall down we'll work on the CRAN side :)

**Comment by z3tt** [comment]
Thanks for the quick answer, that's great to hear! Good luck with the update :)

**Comment by DanRunfola** [comment]
Closing this as we are now on CRAN!
