### ISSUE TITLE
Invalid geometries

### ISSUE THREAD

**Issue by danbebber** [dickoa/rgeoboundaries#12]
Hi - there may be an issue with some of the ADM0 geometries.

library(rgeoboundaries)
library(sf)
world.gb <- gb_adm0(type = "SSCGS")
st_is_valid(world.gb)

...gives 3 errors.

**Comment by dickoa** [comment]
Hi @danbebber,

Thanks for raising this issue. This one is upstream on the data directly, and we can raise it here 
https://github.com/wmgeolab/geoBoundaries/issues

You can reproduce it without the package by downloading the shapefile of the CGAZ dataset (all countries):
It's available in this page: https://www.geoboundaries.org/downloadCGAZ.html

```{r}
world <- read_sf("/vsizip/vsicurl/https://github.com/wmgeolab/geoBoundaries/raw/main/releaseData/CGAZ/geoBoundariesCGAZ_ADM0.zip")
sum(!st_is_valid(world))
```

One workaround, in the meantime, is to use `st_make_valid`.

Best,
Ahmadou

**Comment by DanRunfola** [comment]
We are just about to update the package to work with the new API, @danbebber , which should resolve these issues (as the data being pulled will advance from gb 3.0 to gb 5.0).  Let us know if it still happens after you update the R package once we push the changes (hopefully later today / tomorrow).
