### ISSUE TITLE
XKX invalid name despite being listed as boundaryISO in the metadata

### ISSUE THREAD

**Issue by BrentWHR** [dickoa/rgeoboundaries#14]
XKX seems to be the unofficial ISO-3 code for Kosovo.
Boundaries for Kosovo are available but do not seem to be retrievable with rgeoboundaries.
`all_meta <-  rgeoboundaries::gb_metadata() |> data.table::setDT()
all_meta[boundaryISO == 'XKX']`

Trying to get the boundaries for Kosovo seems to fail:
`rgeoboundaries::geoboundaries('XKX')
rgeoboundaries::geoboundaries('Kosovo')`
The first gives an error, not valid name
The second: ADM0 not available for Kosovo

**Comment by rohith4444** [comment]
The correction was made by fixing country code library, and you should no longer experience any difficulties once the changes are pushed (hopefully within the next two days). If you still encounter a problem after updating the package, please let us know.

**Comment by dickoa** [comment]
Hi @BrentWHR and @rohith4444 

The main issue is also the fact that Kosovo is `XKX` it's not 'officially' in the ISO 3166-1
Alpha 3 standard, it's less likely to land in `countrycode`

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#:~:text=ISO%203166%2D1%20alpha%2D3%20codes%20are%20three%2Dletter,special%20areas%20of%20geographical%20interest.

We can find a way to support it in the package, and other territories in similar situation.

**Comment by DanRunfola** [comment]
Closing this as the immediate issue is resolved.  This may become increasingly challenging as we introduce more territories into gB, which have similar challenges re: if the ISOs are "official" or not.
