### ISSUE TITLE
Error: lexical error: invalid char in json text

### ISSUE THREAD

**Issue by KaiyueZou** [dickoa/rgeoboundaries#15]
Hi, I recently found that I always encounter a new error message when I call any functions of `rgeoboundaries`. I am attaching my code and the detailed error message below. I wonder if this only happens to me or if it's an issue that emerged and happened to others as well. I reinstalled the packages a couple of times, but this issue seems to stay. 

```
> boundary_sf <- rgeoboundaries::gb_adm0("COD")
Error: lexical error: invalid char in json text.
                                       <?php //ini_set('display_errors
                     (right here) ------^
12: parse_string(txt, bigint_as_char)
11: parseJSON(txt, bigint_as_char)
10: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
        simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
        flatten = flatten, ...)
9: fromJSON(res)
8: (function (country = NULL, adm_lvl, type = NULL, version = NULL) 
   {
       iso3 <- country_to_iso3(country)
       assert_type(type)
       assert_version(version)
       if (grepl("^[0-5]$", adm_lvl)) 
           adm_lvl <- paste0("ADM", adm_lvl)
       if (length(iso3) >= 2) {
           urls <- build_urls(iso3, adm_lvl, type, version)
           async_cli <- Async$new(url = urls)
           l <- async_cli$get()
           l <- lapply(seq_along(l), function(i) {
               r <- l[[i]]
               r <- r$parse(encoding = "UTF-8")
               r <- fromJSON(r)
               if (length(r) == 0) 
                   warning(paste(toupper(adm_lvl), "not available for", 
                     country[i]), call. = TRUE)
               r
           })
           do.call(rbind, l)
       }
       else {
           cli <- HttpClient$new(baseurl())
           res <- cli$get(query = list(ISO = toupper(iso3), ADM = toupper(adm_lvl), 
               TYP = toupper(type), VER = toupper(version)))
           res <- res$parse(encoding = "UTF-8")
           res <- fromJSON(res)
           if (length(res) == 0) 
               stop(paste(toupper(adm_lvl), "not available for", 
                   country))
           res
       }
   })(country = country, adm_lvl = adm_lvl, type = type, version = version)
7: eval(mc, parent.frame())
6: eval(mc, parent.frame())
5: withVisible(eval(mc, parent.frame()))
4: gb_meta(country = country, adm_lvl = adm_lvl, type = type, version = version)
3: get_zip_links(country = country, adm_lvl = adm_lvl, type = type, 
       version = version)
2: geoboundaries(country = country, adm_lvl = "adm0", type = type, 
       version = version, quiet = quiet)
1: rgeoboundaries::gb_adm0("COD")
```

Thank you!

**Comment by DanRunfola** [comment]
Hey!

Apologies on the slow response, as we haven't (to date) directly maintained this repository (many thanks to the community who has been working on it to date).

I had originally planned to deprecate our old API (https://www.geoboundaries.org/gbRequest.html?ISO=USA) with gb 5.0, but didn't realize the R package was relying on it until I saw this message.  I just re-activated the old API, accordingly.

My plan going forward is to upgrade the R package so it uses our new API, then after that I'll deprecate the old API in ~6.0.

Sorry about the gap in provision.

Dan

**Comment by DanRunfola** [comment]
And, just in case anyone @dickoa picks this up before me, the new API is very, very similar, just with different endpoints.

I.e.: https://www.geoboundaries.org/gbRequest.html?ISO=USA
is now 
https://www.geoboundaries.org/api/current/gbOpen/USA/ALL/

Full path:
https://www.geoboundaries.org/api/current/gbOpen/[3-LETTER-ISO-CODE]/[ADM-LEVEL]/

**Comment by dickoa** [comment]
Thanks @KaiyueZou and @DanRunfola 

I'll update the code to use the latest version and API, and hopefully this'll be fixed!
Ahmadou

**Comment by rohith4444** [comment]
@KaiyueZou, the package has been updated to be compatible with the new API. We hope to implement the changes within 2 days and anticipate no further problems. If you encounter any issues after updating the package, please let us know.

**Comment by QLLZ** [comment]
The same issue seems to happen again when I tried the gb_adm("COD") today. 

Here's the error: 
```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
```

**Comment by DanRunfola** [comment]
Hi @QLLZ  - could you confirm if you're using the current version of the package?  We just pushed a big update (including a deprecation of an old API), so users will need to update with remotes::install_github("wmgeolab/rgeoboundaries") .

If you've already done this, we'll dig in.

**Comment by QLLZ** [comment]
@DanRunfola it worked after I reinstalled the package ! Thank you!

**Comment by DanRunfola** [comment]
Great!  I'm going to close this out for now.  Let me know if anything new comes up - we've had some test users on the new R Package update, but it went live ~yesterday, so there may still be kinks to work out.
