### ISSUE TITLE
how best to query which admin levels are available for a country

### ISSUE THREAD

**Issue by andysouth** [dickoa/rgeoboundaries#2]
Hi @dickoa,

What do you think is the best way of querying which admin levels are available for a particular combination of country and boundary type ? 

I would like to allow users to query that before they download the data, e.g. to compare to other data sources.

I see also that in some cases different levels are available according to the licence (open or humanitarian).

I see that this url returns different admin levels and licences and defaults to one TYP - I guess that all TYP options are available for the entries returned here. 

https://www.geoboundaries.org/gbRequest.html?ISO=AGO&ADM=ALL  

Thanks !

Andy

**Comment by dickoa** [comment]
Hi @andysouth,
 
I hope all is good. I can write a function that can check if a data is available in the package.
An easier way to check is to download for each version of the database the global csv files and query it, here's the link for v3.0.0

https://www.geoboundaries.org/data/geoBoundaries-3_0_0/geoBoundaries-3_0_0.csv  

I can add this data as a dataset in rgeoboundaries and write a wrapper to check admin availability.

Thanks,
Ahmadou

**Comment by andysouth** [comment]
Hi @dickoa,

I'm well thanks, hope you are too.
Yes, that would be useful. I see that licence information is in there too.
I could write something if you are pressed for time ?

cheers,
Andy

**Comment by dickoa** [comment]
Hi @andysouth,

I rewrote `gb_metadata` and now it's base on a internal data.frame and no longer calls the API. 
I just pushed the change.

```r
library(rgeoboundaries)
gb_metadata("AGO", "ALL")
##            boundaryID boundaryISO boundaryYear boundaryType
## 14 AGO-ADM0-3_0_0-G14         AGO         2017         ADM0
## 15 AGO-ADM1-3_0_0-G15         AGO         2017         ADM1
## 16 AGO-ADM2-3_0_0-G16         AGO         2018         ADM2
## 17 AGO-ADM3-3_0_0-G17         AGO         2018         ADM3
##       boundarySource-1
## 14       OpenStreetMap
## 15       OpenStreetMap
## 16 Human Data Exchange
## 17 Human Data Exchange
##                                                             boundarySource-2
## 14                                                                 Wambacher
## 15                                                                 Wambacher
## 16 United Nations Office for the Coordination of Humanitarian Affairs, ROSEA
## 17 United Nations Office for the Coordination of Humanitarian Affairs, ROSEA
##                                boundaryLicense
## 14 Open Data Commons Open Database License 1.0
## 15 Open Data Commons Open Database License 1.0
## 16                        Other - Humanitarian
## 17                        Other - Humanitarian
##                                    licenseDetail
## 14   Open Data Commons Open Database License 1.0
## 15   Open Data Commons Open Database License 1.0
## 16 Humanitarian use only - Noted in metadata tab
## 17 Humanitarian use only - Noted in metadata tab
##                                                        licenseSource
## 14                           https://www.openstreetmap.org/copyright
## 15                           https://www.openstreetmap.org/copyright
## 16 https://data.humdata.org/dataset/angola-administrative-levels-0-3
## 17 https://data.humdata.org/dataset/angola-administrative-levels-0-3
##                                                    boundarySourceURL
## 14                        https://wambachers-osm.website/boundaries/
## 15                        https://wambachers-osm.website/boundaries/
## 16 https://data.humdata.org/dataset/angola-administrative-levels-0-3
## 17 https://data.humdata.org/dataset/angola-administrative-levels-0-3
##    boundaryUpdate
## 14     2020-05-25
## 15     2020-05-25
## 16     2020-05-25
## 17     2020-05-25
##                                                                                         downloadURL
## 14 https://geoboundaries.org/data/geoBoundaries-3_0_0/AGO/ADM0/geoBoundaries-3_0_0-AGO-ADM0-all.zip
## 15 https://geoboundaries.org/data/geoBoundaries-3_0_0/AGO/ADM1/geoBoundaries-3_0_0-AGO-ADM1-all.zip
## 16 https://geoboundaries.org/data/geoBoundaries-3_0_0/AGO/ADM2/geoBoundaries-3_0_0-AGO-ADM2-all.zip
## 17 https://geoboundaries.org/data/geoBoundaries-3_0_0/AGO/ADM3/geoBoundaries-3_0_0-AGO-ADM3-all.zip
##    boundaryVersion
## 14           3_0_0
## 15           3_0_0
## 16           3_0_0
## 17           3_0_0
```

I can also add another wrapper `gb_is_available` that returns TRUE/FALSE for each admin level possible, let me know what would be the desired output. Let me know if you have a specific output in mind.

Thanks

**Comment by andysouth** [comment]
Thanks @dickoa,
 
That's really useful, and yes `gb_is_available` would be helpful too, maybe with an optional `boundaryLicense` argument.

Would also be helpful to have something like `gb_max_adm(country, boundaryLicense)` that returns the max admin level available for a country and optional license restriction.

**Comment by dickoa** [comment]
Hi @andysouth 

I'm looking into this but I'm not sure we have a defined list of license to use it as a parameter. I wrote a function who does this:

```r
gb_max_adm_lvl(c("senegal", "france", "nigeria"))
##   country                                     license
## 1  France Open Data Commons Open Database License 1.0
## 2 Nigeria                   Other - Direct Permission
## 3 Nigeria                        Other - Humanitarian
## 4 Senegal                        Other - Humanitarian
##   max_adm_lvl
## 1        ADM4
## 2        ADM2
## 3        ADM0
## 4        ADM3
```

I'm not sure also "max" is the right word but don't have anything better. I'm open to suggestion. Let me know what will be the desired output for your use case too or if this one is OK.

Ahmadou

**Comment by andysouth** [comment]
Thanks ! That looks great. My use case is that I want to be able to check what is the most detailed level available for a country, partly to be able to warn if users try to exceed that.

If you could add an optional license filter then it would make it easier for users to specify a licence of their choice.

Small detail, but it would be useful, if admin level was returned as an integer, to make it easier to test against. Relatedly I wonder if it might be better to have the `adm_lvl` argument to geoboundaries() be an integer too. 

In my use case ideally I would like to be able to call : 
gb_max_adm_lvl("nigeria") # would return 2 in your e.g. above
gb_max_adm_lvl(c("senegal","nigeria")) # would return c(3,2) 
gb_max_adm_lvl("nigeria", license="Other - Humanitarian") # would return 0 in your example

There would also be the potential for it to return NULL if no admin levels available for that license.

Happy to discuss on slack if helpful.

Andy

**Comment by dickoa** [comment]
Thanks for example and I also thought about allowing adm_lvl to be an integer. I hesitated a lot but can allow both type of inputs even if it's not "clean" programmatically.
Here's the new function and I decided to throw an error if the license doesn't exist but happy to have NULL or NA instead when the license doesn't exist.

```r
gb_max_adm_lvl("nigeria")
## nigeria
##       2

gb_max_adm_lvl(c("senegal","nigeria"))
## senegal nigeria
##       3       2

gb_max_adm_lvl("nigeria", license = "Other - Humanitarian")
## nigeria
##       0

gb_max_adm_lvl(c("fra", "senegal", "nigeria"), license = "Other - Direct Permission")
## ##    fra senegal nigeria 
## ##     NA      NA       2 

gb_max_adm_lvl("nigeria", license = "New license")
## ## Error in gb_max_adm_lvl("nigeria", license = "New license") :
## ##   License not available!
```

Ahmadou

**Comment by dickoa** [comment]
Also added support for single character '0', '1', ..., '5' or any integers between 0 and 5

```r
all.equal(geoboundaries("mali", 2), geoboundaries("mali", "adm2"))
## [1] TRUE
```

I can push it if it's fine for you.
Ahmadou

**Comment by andysouth** [comment]
Sounds perfect ! Thanks.
Andy

**Comment by dickoa** [comment]
Just pushed all changes. I will close this issue but feel free to reopen in case something is not working as expected or is broken.
Ahmadou
