### ISSUE TITLE
Lexical error in gb_adm1()

### ISSUE THREAD

**Issue by AaronPlex** [dickoa/rgeoboundaries#24]
It seems that the function below has an error that I could not find a solution for. I have used this function previously and it was working successfully, but not today :(.

`library(rgeoboundaries)
egy <- gb_adm1("EGY")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^`

**Comment by DanRunfola** [comment]
Hi @AaronPlex - have you upgraded to the most recent version of rGeoboundaries?  We deprecated an old API the original version relied on, and have updated the package accordingly. 

See: https://github.com/wmgeolab/rgeoboundaries/issues/20

**Comment by AaronPlex** [comment]
Excellent, thanks.

**Comment by DanRunfola** [comment]
Closing this out - let me know if that doesn't fix the issue!
