### ISSUE TITLE
Incorrect Argentinian provinces?

### ISSUE THREAD

**Issue by noahdasanaike** [dickoa/rgeoboundaries#25]
Seems that Entre Ríos is missing from rgeoboundaries::gb_adm1(country = "Argentina").

**Comment by DanRunfola** [comment]
Could you please report this over on the main geoBoundaries repo?

https://github.com/wmgeolab/geoBoundaries/issues/new?assignees=&labels=&projects=&template=boundary-errata.md&title=%5BBOUNDARY+ERRATA%5D

I'm going to close it here, as we use this for issues specific to the R package.
