### ISSUE TITLE
Feature request: add canonical names for ADM from geoBoundaries 4.0.0

### ISSUE THREAD

**Issue by charliejhadley** [dickoa/rgeoboundaries#8]
In geoBoundaries 4.0 the API will include canonical names for ADM as per https://github.com/wmgeolab/geoBoundaries/issues/161#event-4663168889.

It would be great for rgeoboundaries to add this information to the tibbles returned by `gb_adm*()`.

**Comment by DanRunfola** [comment]
Just one quick note on this (I maintain the core geoboundaries repo, so will defer to the R pros here) - we don't currently have full coverage for canonical names, but are working towards 100%.  I would estimate that by the end of this year we'll be pretty close, and we do have pretty decent coverage now.  Just to caveat :)

Dan

**Comment by rohith4444** [comment]
@charliejhadley, boundary canonical names have been added to the tibble returned by gb_adm*(). You should be able to see these changes once they are pushed (hopefully within the next two days). If you do not see them in the output after updating the package, please inform us.

**Comment by DanRunfola** [comment]
Closing this out as a cleanup - looks like we implemented this succesfully last round.
