### ISSUE TITLE
Installation failing on 4.0.2

### ISSUE THREAD

**Issue by danielreispereira** [dickoa/rgeoboundaries#9]
Error: .onLoad failed in loadNamespace() for 'units', details:
  call: udunits_init(path)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
Execution halted
ERROR: lazy loading failed for package 'rgeoboundaries'

**Comment by dickoa** [comment]
Hi @danielreispereira,

In which OS this is failing ?
Do you have the `units` package working, can you check or install the `units` package.
I suspect the issue is with the `units` package and not directly `rgeoboundaries`.

Best,

**Comment by DanRunfola** [comment]
Closing this out as stale with no response, @danielreispereira if this is still an issue please let us know, as we are just about to push an upgrade to the package!
